name: Build and deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ "main" ]

env:
  ZINE_VERSION: v0.8.0

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build and deploy
      run: ./deploy.sh
    